### ISSUE TITLE
Переопределение тестируемого сайта требует пересборки докера

### ISSUE THREAD

**Issue by qertis** [ngadiyak/Demo#3]
https://github.com/ngadiyak/Demo/blob/f2634e1098d98aab4d62ee8fed3382fe6e5a44dc/Dockerfile#L4

Удобнее было бы это перенести в аргументы запускаемого скрипта в npm

**Comment by ngadiyak** [comment]
в докерфайле просто указано дефолтное значение переменной среды, которое используется потом в [конфиге ](https://github.com/ngadiyak/Demo/blob/master/codecept.conf.js#L15) тестов

соот-но пересборка не нужна, достаточно в команду запуска контейнера добавить `docker run -e 'BASE_URL=${url}' ...`

**Comment by ngadiyak** [comment]
https://github.com/ngadiyak/Demo/pull/8
