### ISSUE TITLE
Абстрактные имена тестов

### ISSUE THREAD

**Issue by qertis** [ngadiyak/Demo#5]
https://github.com/ngadiyak/Demo/blob/f2634e1098d98aab4d62ee8fed3382fe6e5a44dc/tests/demoTest.js#L5

По ним сложно ориентироваться

**Comment by ngadiyak** [comment]
какие написали в задании, такие и указал =)

переделал на более человеческие

**Comment by ngadiyak** [comment]
https://github.com/ngadiyak/Demo/pull/8
