### ISSUE TITLE
Ускорение вычисления

### ISSUE THREAD

**Issue by qertis** [ngadiyak/Demo#6]
https://github.com/ngadiyak/Demo/blob/f2634e1098d98aab4d62ee8fed3382fe6e5a44dc/helpers/imageHelper.js#L16

Как вариант разбивать изображение на сегменты размером `20x20px` и проводить вычисления параллельно

**Comment by ngadiyak** [comment]
схема работает крайне медленно, а картинка обрабатывается меньше, чем за секунду, поэтому, даже если я напишу `y = y + 0.001`, вместо `y++`, время выполнения теста значительно не изменится.

но ок, сделал сделал 20х20

**Comment by ngadiyak** [comment]
https://github.com/ngadiyak/Demo/pull/8
